"""Genome-scale data, scoring, calibration, and optional model adapters."""

from rejuvenationkit.genomics.adapters import (
    annotate_feature_overlaps,
    beta_to_m_values,
    from_anndata,
    from_expression_frame,
    from_methylation_beta,
    normalize_counts_log_cpm,
    read_vcf_dosage,
)
from rejuvenationkit.genomics.calibration import (
    GenomicPrediction,
    GenomicPredictionBatch,
    GenomicTargetCalibrator,
    GenomicTargetConfig,
)
from rejuvenationkit.genomics.effects import FeatureEffect, read_feature_effects
from rejuvenationkit.genomics.huggingface import (
    EmbeddingBatch,
    EmbeddingProvenance,
    GenomeEmbedder,
    HFGenomeEmbedder,
    HFGenomeEncoderConfig,
    HFModelClass,
    OverlengthPolicy,
    PoolingStrategy,
    SequenceWindow,
    StrandPolicy,
    VariantEmbedding,
)
from rejuvenationkit.genomics.orthologs import (
    OrthologAmbiguityPolicy,
    OrthologMap,
    OrthologRecord,
    OrthologTranslation,
    translate_signature,
)
from rejuvenationkit.genomics.schemas import (
    FeatureNamespace,
    GenomicFeature,
    GenomicFeatureType,
    GenomicMatrix,
    GenomicMatrixProvenance,
    GenomicSample,
    MatrixScale,
)
from rejuvenationkit.genomics.signatures import (
    GeneSignature,
    MissingFeaturePolicy,
    SignatureContrastBatch,
    SignatureContrastConfig,
    SignatureEstimate,
    SignatureFeature,
    SignatureScores,
    aggregate_feature_effects,
    estimate_signature_contrast,
    estimate_signature_contrasts,
    score_weighted_signature,
)

__all__ = [
    "EmbeddingBatch",
    "EmbeddingProvenance",
    "FeatureEffect",
    "FeatureNamespace",
    "GeneSignature",
    "GenomeEmbedder",
    "GenomicFeature",
    "GenomicFeatureType",
    "GenomicMatrix",
    "GenomicMatrixProvenance",
    "GenomicPrediction",
    "GenomicPredictionBatch",
    "GenomicSample",
    "GenomicTargetCalibrator",
    "GenomicTargetConfig",
    "HFGenomeEmbedder",
    "HFGenomeEncoderConfig",
    "HFModelClass",
    "MatrixScale",
    "MissingFeaturePolicy",
    "OrthologAmbiguityPolicy",
    "OrthologMap",
    "OrthologRecord",
    "OrthologTranslation",
    "OverlengthPolicy",
    "PoolingStrategy",
    "SequenceWindow",
    "SignatureContrastBatch",
    "SignatureContrastConfig",
    "SignatureEstimate",
    "SignatureFeature",
    "SignatureScores",
    "StrandPolicy",
    "VariantEmbedding",
    "aggregate_feature_effects",
    "annotate_feature_overlaps",
    "beta_to_m_values",
    "estimate_signature_contrast",
    "estimate_signature_contrasts",
    "from_anndata",
    "from_expression_frame",
    "from_methylation_beta",
    "normalize_counts_log_cpm",
    "read_feature_effects",
    "read_vcf_dosage",
    "score_weighted_signature",
    "translate_signature",
]
